USE [HoSoNoiVu]
GO

/****** Object:  Table [dbo].[LoaiVanBan]    Script Date: 7/1/2022 9:13:48 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[LoaiVanBan](
	[DocTypeId] [int] IDENTITY(1,1) NOT NULL,
	[DocTypeName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_LoaiVanBan] PRIMARY KEY CLUSTERED 
(
	[DocTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


