USE [HoSoNoiVu]
GO

/****** Object:  Table [dbo].[HoSo_VanBan]    Script Date: 7/1/2022 9:13:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[HoSo_VanBan](
	[FileCode] [nvarchar](60) NOT NULL,
	[DocCode] [char](25) NOT NULL,
 CONSTRAINT [PK_Files_Doc] PRIMARY KEY CLUSTERED 
(
	[FileCode] ASC,
	[DocCode] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[HoSo_VanBan]  WITH CHECK ADD  CONSTRAINT [FK__HoSo_VanB__DocCo__48CFD27E] FOREIGN KEY([DocCode])
REFERENCES [dbo].[VanBan] ([DocCode])
GO

ALTER TABLE [dbo].[HoSo_VanBan] CHECK CONSTRAINT [FK__HoSo_VanB__DocCo__48CFD27E]
GO

ALTER TABLE [dbo].[HoSo_VanBan]  WITH CHECK ADD  CONSTRAINT [FK__HoSo_VanB__FileC__47DBAE45] FOREIGN KEY([FileCode])
REFERENCES [dbo].[HoSoLuuTru] ([FileCode])
GO

ALTER TABLE [dbo].[HoSo_VanBan] CHECK CONSTRAINT [FK__HoSo_VanB__FileC__47DBAE45]
GO


