USE [HoSoNoiVu]
GO

/****** Object:  Table [dbo].[TLAnh_TLDiKem]    Script Date: 7/1/2022 9:15:00 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TLAnh_TLDiKem](
	[DocAttachedId] [int] NOT NULL,
	[ImageId] [int] NOT NULL,
	[DocAttached] [varbinary](max) NULL,
	[Extension] [char](4) NULL,
 CONSTRAINT [PK_TLAnh_TLDiKem] PRIMARY KEY CLUSTERED 
(
	[DocAttachedId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

ALTER TABLE [dbo].[TLAnh_TLDiKem]  WITH CHECK ADD  CONSTRAINT [FK_TLAnh_TLDiKem_TLAnh] FOREIGN KEY([ImageId])
REFERENCES [dbo].[TLAnh] ([ImageId])
GO

ALTER TABLE [dbo].[TLAnh_TLDiKem] CHECK CONSTRAINT [FK_TLAnh_TLDiKem_TLAnh]
GO


